# **Notebook 2. Manipulasi Data dengan Pandas**

![Code](https://media.giphy.com/media/PiQejEf31116URju4V/giphy.gif)

**Pandas** adalah sebuah library di Python yang berlisensi BSD dan open source yang menyediakan struktur data dan analisis data yang mudah digunakan. Pandas biasa digunakan untuk membuat tabel, mengubah dimensi data, mengecek data, dan lain sebagainya. Struktur data dasar pada Pandas dinamakan DataFrame, yang memudahkan kita untuk membaca sebuah file dengan banyak jenis format seperti file .txt, .csv, dan .tsv. Fitur ini akan menjadikannya table dan juga dapat mengolah suatu data dengan menggunakan operasi seperti join, distinct, group by, agregasi, dan teknik lainnya yang terdapat pada SQL.
Pandas serupa dengan dplyr pada bahasa pemrograman R

In [3]:
import pandas as pd # load library pandas
import numpy as np # load library numpy

# Struktur Data Pandas

Terdapat 3 struktur data pada pandas:

- **Series** (1D): struktur data homogen, data value *mutable* dan *size-immutable*
- **DataFrame** (2D): struktur data heterogen, tabular, data value *mutable* dan *size-mutable*
- **Panels** (3D): struktur data dengan *size-mutable* array

The best way to think of these data structures is that the higher dimensional data structure is a container of its lower dimensional data structure. For example, DataFrame is a container of Series, Panel is a container of DataFrame. (*tutorialspoint.com*)

## Series

In [2]:
vektor_a = np.array(range(10))
vektor_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
series_a = pd.Series(vektor_a)
series_a

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [5]:
vektor_b = {'indeks_1': 1, 'indeks_2': np.array(range(9))}
series_b = pd.Series(vektor_b)
series_b

indeks_1                              1
indeks_2    [0, 1, 2, 3, 4, 5, 6, 7, 8]
dtype: object

In [5]:
# ambil nilai series_a pada indeks ke-8
series_a[8]

8

In [4]:
# ambil nilai series_b untuk indeks ke-1
series_b[1]

NameError: name 'series_b' is not defined

In [7]:
# cek tipe data series_a
type(series_a)

pandas.core.series.Series

## Dataframe

In [2]:
# membuat dataframe dari list/array
vektor_a = np.arange(10)
tabel_a = pd.DataFrame(vektor_a)
tabel_a

NameError: name 'np' is not defined

In [9]:
# membuat dataframe dari set
vektor_a = np.arange(10)
vektor_b = np.random.rand(10)
tabel_a = pd.DataFrame({'a':vektor_a,'b':vektor_b}) # create dataframe from set
tabel_a

   a         b
0  0  0.166373
1  1  0.510958
2  2  0.709455
3  3  0.680167
4  4  0.194396
5  5  0.975170
6  6  0.057416
7  7  0.457798
8  8  0.041049
9  9  0.866426

In [10]:
# membuat DataFrame dari list of dictionaries
dictionary_b = [{'nilai_a':1, 'nilai_b':2, 'nilai_c':10}, {'nilai_a':10, 'nilai_b':10, 'nilai_c':20}]
tabel_b = pd.DataFrame(dictionary_b)
tabel_b

   nilai_a  nilai_b  nilai_c
0        1        2       10
1       10       10       20

In [11]:
# mengganti indeks
tabel_b = pd.DataFrame(dictionary_b, index=['baris_1','baris_2'])
tabel_b

         nilai_a  nilai_b  nilai_c
baris_1        1        2       10
baris_2       10       10       20

In [12]:
# Membaca file csv dengan pd.read_csv(nama_file, delimiter)
df = pd.read_csv('https://raw.githubusercontent.com/Anubhavkumar45/Absenteeism-at-work/master/Absenteeism_at_work.csv', delimiter=';')
df

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14,7,3,1,289,36,13,33,264.604,...,0,1,2,1,0,1,90,172,30,8
736,1,11,7,3,1,235,11,14,37,264.604,...,0,3,1,0,0,1,88,172,29,4
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0

Jika suatu variabel memiliki tipe tertentu, maka variabel tersebut biasanya akan memuat method yang bisa digunakan. Kita dapat melihat *method* yang terdapat dalam sebuah objek dengan menggunakan fungsi ```dir(objek)```.

In [13]:
dir(df)

['Age',
 'Education',
 'Height',
 'ID',
 'Pet',
 'Seasons',
 'Son',
 'T',
 'Weight',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

value pada objek dataframe salah satunya adalah ```shape``` yang berfungsi untuk mengetahui dimensi dari dataframe tersebut.

In [14]:
df.shape

(740, 21)

value pada objek dataframe yang menyimpan daftar nama kolom adalah ```columns```.

In [15]:
df.columns

Index(['ID', 'Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Transportation expense', 'Distance from Residence to Work',
       'Service time', 'Age', 'Work load Average/day ', 'Hit target',
       'Disciplinary failure', 'Education', 'Son', 'Social drinker',
       'Social smoker', 'Pet', 'Weight', 'Height', 'Body mass index',
       'Absenteeism time in hours'],
      dtype='object')

Method pada objek dataframe yang dapat digunakan untuk memeriksa sebaran data secara deskriptif dari setiap kolom pada dataframe adalah ```describe()```.

In [16]:
df.describe()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
count,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,...,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000
mean,18.017568,19.216216,6.324324,3.914865,2.544595,221.329730,29.631081,12.554054,36.450000,271.490235,...,0.054054,1.291892,1.018919,0.567568,0.072973,0.745946,79.035135,172.114865,26.677027,6.924324
std,11.021247,8.433406,3.436287,1.421675,1.111831,66.952223,14.836788,4.384873,6.478772,39.058116,...,0.226277,0.673238,1.098489,0.495749,0.260268,1.318258,12.883211,6.034995,4.285452,13.330998
min,1.000000,0.000000,0.000000,2.000000,1.000000,118.000000,5.000000,1.000000,27.000000,205.917000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,56.000000,163.000000,19.000000,0.000000
25%,9.000000,13.000000,3.000000,3.000000,2.000000,179.000000,16.000000,9.000000,31.000000,244.387000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,69.000000,169.000000,24.000000,2.000000
50%,18.000000,23.000000,6.000000,4.000000,3.000000,225.000000,26.000000,13.000000,37.000000,264.249000,...,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,83.000000,170.000000,25.000000,3.000000
75%,28.000000,26.000000,9.000000,5.000000,4.000000,260.000000,50.000000,16.000000,40.000000,294.217000,...,0.000000,1.000000,2.000000,1.000000,0.000000,1.000000,89.000000,172.000000,31.000000,8.000000
max,36.000000,28.000000,12.000000,6.000000,4.000000,388.000000,52.000000,29.000000,58.000000,378.884000,...,1.000000,4.000000,4.000000,1.000000,1.000000,8.000000,108.000000,196.000000,38.000000,120.000000

# Modify Dataset

Pandas mendukung kemudahan untuk memodifikasi dataset yang akan digunakan dalam analisis. Modifikasi data tersebut antara lain terdiri dari data selection, filtering, sorting, mutate, compute, dan merge.

## Selecting Data

In [17]:
## Memilih data dengan output berupa series
df.Education

0      1
1      1
2      1
3      1
4      1
      ..
735    1
736    3
737    1
738    1
739    1
Name: Education, Length: 740, dtype: int64

In [18]:
type(df.Education)

pandas.core.series.Series

In [19]:
## Memilih data dengan output berupa series
df['Education']

0      1
1      1
2      1
3      1
4      1
      ..
735    1
736    3
737    1
738    1
739    1
Name: Education, Length: 740, dtype: int64

In [20]:
## Memilih data dengan output berupa dataframe
df[['Education']]

     Education
0            1
1            1
2            1
3            1
4            1
..         ...
735          1
736          3
737          1
738          1
739          1

[740 rows x 1 columns]

In [21]:
type(df[['Education']])

pandas.core.frame.DataFrame

In [22]:
# memilih data berdasarkan beberapa nama kolom.

df[['Reason for absence','Education']]

     Reason for absence  Education
0                    26          1
1                     0          1
2                    23          1
3                     7          1
4                    23          1
..                  ...        ...
735                  14          1
736                  11          3
737                   0          1
738                   0          1
739                   0          1

[740 rows x 2 columns]

Kita dapat memilih kolom berdasarkan tipe data pada kolom dengan menggunakan method ```select_dtypes(tipe_data)```.

Ada beberapa tipe data yang terdapat pada objek ```pandas```, diantaranya:

- float (bilangan numerik dengan desimal)
- int (bilangan bulat)
- object (list, dictionary, character, dan lainnya)
- boolean (```True```, ```False```)
- category

In [23]:
## Memilih kolom dengan kategori float
df.select_dtypes(include = 'float')

     Work load Average/day
0                   239.554
1                   239.554
2                   239.554
3                   239.554
4                   239.554
..                      ...
735                 264.604
736                 264.604
737                 271.219
738                 271.219
739                 271.219

[740 rows x 1 columns]

In [24]:
## Memilih kolom dengan beberapa kategori numerik
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

df.select_dtypes(include = numerics)

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14,7,3,1,289,36,13,33,264.604,...,0,1,2,1,0,1,90,172,30,8
736,1,11,7,3,1,235,11,14,37,264.604,...,0,3,1,0,0,1,88,172,29,4
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0

In [25]:
# memilih data pada baris tertentu
df.loc[[1],]

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0

In [26]:
# memilih data pada baris tertentu
df.loc[range(0,5),]

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2

In [27]:
# memilih data pada baris tertentu dan kolom tertentu
df.loc[range(0,5),['Seasons','Age']]

   Seasons  Age
0        1   33
1        1   50
2        1   38
3        1   39
4        1   33

In [28]:
# memilih data menggunakan loc
df.loc[0:4]

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2

In [29]:
# memilih data menggunakan iloc
df.iloc[0:4]

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4

## Filtering

Subset the dataframe rows or columns according to the specified index labels.

In [30]:
df.head(10) # Calling the first 10 rows of data from dataset

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
5,3,23,7,6,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
6,10,22,7,6,1,361,52,3,28,239.554,...,0,1,1,1,0,4,80,172,27,8
7,20,23,7,6,1,260,50,11,36,239.554,...,0,1,4,1,0,0,65,168,23,4
8,14,19,7,2,1,155,12,14,34,239.554,...,0,1,2,1,0,0,95,196,25,40
9,1,22,7,2,1,235,11,14,37,239.554,...,0,3,1,0,0,1,88,172,29,8

In [31]:
df.tail(10) # Calling the last 10 rows of data from dataset

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
730,6,22,7,3,1,189,29,13,33,264.604,...,0,1,2,0,0,2,69,167,25,16
731,34,23,7,4,1,118,10,10,37,264.604,...,0,1,0,0,0,0,83,172,28,2
732,10,22,7,4,1,361,52,3,28,264.604,...,0,1,1,1,0,4,80,172,27,8
733,28,22,7,4,1,225,26,9,28,264.604,...,0,1,1,0,0,2,69,169,24,8
734,13,13,7,2,1,369,17,12,31,264.604,...,0,1,3,1,0,0,70,169,25,80
735,11,14,7,3,1,289,36,13,33,264.604,...,0,1,2,1,0,1,90,172,30,8
736,1,11,7,3,1,235,11,14,37,264.604,...,0,3,1,0,0,1,88,172,29,4
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0

In [32]:
df_filtered = df[df['Age']>30] # Boolean indexing
df_filtered

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14,7,3,1,289,36,13,33,264.604,...,0,1,2,1,0,1,90,172,30,8
736,1,11,7,3,1,235,11,14,37,264.604,...,0,3,1,0,0,1,88,172,29,4
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0

In [33]:
rule1 = df['Age']>30
rule2 = df['Age']<50

df_filtered = df[rule1 & rule2] # Boolean indexing
df_filtered

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
5,3,23,7,6,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,13,13,7,2,1,369,17,12,31,264.604,...,0,1,3,1,0,0,70,169,25,80
735,11,14,7,3,1,289,36,13,33,264.604,...,0,1,2,1,0,1,90,172,30,8
736,1,11,7,3,1,235,11,14,37,264.604,...,0,3,1,0,0,1,88,172,29,4
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0

In [34]:
# filter menggunakan fungsi isin

df_filtered = df[df['Age'].isin([30,40,50])] # Boolean indexing
df_filtered

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
47,15,23,9,5,1,291,31,12,40,241.476,...,0,1,1,1,0,1,73,171,25,4
49,15,14,9,2,4,291,31,12,40,241.476,...,0,1,1,1,0,1,73,171,25,32
55,36,0,9,3,4,118,13,18,50,241.476,...,1,1,1,1,0,0,98,178,31,0
64,36,0,10,4,4,118,13,18,50,253.465,...,1,1,1,1,0,0,98,178,31,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,36,19,6,5,3,118,13,18,50,275.089,...,0,1,1,1,0,0,98,178,31,3
717,22,13,6,5,3,179,26,9,30,275.089,...,0,3,0,0,0,0,56,171,19,2
718,15,28,6,5,3,291,31,12,40,275.089,...,0,1,1,1,0,1,73,171,25,2
719,22,13,6,2,1,179,26,9,30,275.089,...,0,3,0,0,0,0,56,171,19,3
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0

In [35]:
# filter menggunakan negasi fungsi isin

df_filtered = df[~df['Age'].isin([30,40,50])] # Boolean indexing
df_filtered

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
5,3,23,7,6,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,13,13,7,2,1,369,17,12,31,264.604,...,0,1,3,1,0,0,70,169,25,80
735,11,14,7,3,1,289,36,13,33,264.604,...,0,1,2,1,0,1,90,172,30,8
736,1,11,7,3,1,235,11,14,37,264.604,...,0,3,1,0,0,1,88,172,29,4
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0

In [36]:
# filtering data menggunakan query

df.query('Age > 30 & Age < 50')

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
5,3,23,7,6,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,13,13,7,2,1,369,17,12,31,264.604,...,0,1,3,1,0,0,70,169,25,80
735,11,14,7,3,1,289,36,13,33,264.604,...,0,1,2,1,0,1,90,172,30,8
736,1,11,7,3,1,235,11,14,37,264.604,...,0,3,1,0,0,1,88,172,29,4
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0

## Checking Missing Value

Pada kondisi data yang sebenarnya, data yang akan digunakan umumnya tidak terlepas dari missing value. Untuk itu perlu dilakukan pengecekan data untuk memastikan kondisi data dan apabila ditemukan missing value, maka perlu ada treatment khusus untuk mengatasi hal tersebut.

In [37]:
df_missing = pd.DataFrame(np.random.randn(10,5))
df_missing[df_missing > 0.9] = np.nan
df_missing

          0         1         2         3         4
0 -0.179966 -0.075511  0.073180  0.324563 -0.264312
1 -0.194696  0.810472 -0.685158  0.101977 -0.407892
2 -1.333147 -3.013537       NaN  0.456716 -0.045316
3       NaN -1.554259 -0.931851 -0.687379  0.384596
4  0.676005 -1.414156       NaN -0.055454 -1.744075
5  0.608261 -0.306487 -0.653793 -0.091076 -0.556868
6 -0.169525       NaN -0.372254       NaN -1.177063
7 -0.232572 -0.606088 -0.107531 -0.748381  0.302155
8 -0.464510  0.301084       NaN  0.094478 -0.290425
9 -0.143337 -1.222043 -1.326520 -1.192843  0.718895

In [38]:
## Memeriksa apakah terdapat missing value pada dataframe
df_missing.isna().any()

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [39]:
## Memeriksa berapa banyak data yang missing untuk setiap kolom
df_missing.isnull().sum()

0    1
1    1
2    3
3    1
4    0
dtype: int64

Jika terdapat missing value pada dataframe dan kita ingin menghapus record dengan missing value tersebut, method yang dapat digunakan adalah ```dropna()```

In [40]:
df_dropmissing = df_missing.dropna()
df_dropmissing

          0         1         2         3         4
0 -0.179966 -0.075511  0.073180  0.324563 -0.264312
1 -0.194696  0.810472 -0.685158  0.101977 -0.407892
5  0.608261 -0.306487 -0.653793 -0.091076 -0.556868
7 -0.232572 -0.606088 -0.107531 -0.748381  0.302155
9 -0.143337 -1.222043 -1.326520 -1.192843  0.718895

## Sorting data

Sort by the values along either axis.

In [41]:
df.sort_values('Age')

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
132,27,23,1,5,2,184,42,7,27,308.593,...,0,1,0,0,0,0,58,167,21,2
137,27,23,2,6,2,184,42,7,27,302.585,...,0,1,0,0,0,0,58,167,21,1
209,27,7,5,4,3,184,42,7,27,378.884,...,0,1,0,0,0,0,58,167,21,4
118,27,23,1,5,2,184,42,7,27,308.593,...,0,1,0,0,0,0,58,167,21,2
149,27,23,2,3,2,184,42,7,27,302.585,...,0,1,0,0,0,0,58,167,21,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,9,25,3,3,2,228,14,16,58,222.196,...,0,1,2,0,0,1,65,172,22,3
622,9,12,3,3,2,228,14,16,58,222.196,...,0,1,2,0,0,1,65,172,22,112
640,9,25,3,4,2,228,14,16,58,222.196,...,0,1,2,0,0,1,65,172,22,2
255,9,18,8,3,1,228,14,16,58,265.615,...,0,1,2,0,0,1,65,172,22,8
434,9,18,5,4,3,228,14,16,58,246.074,...,0,1,2,0,0,1,65,172,22,8

In [42]:
## Sort values secara descending

df.sort_values('Age',ascending=False)

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
434,9,18,5,4,3,228,14,16,58,246.074,...,0,1,2,0,0,1,65,172,22,8
729,9,6,7,3,1,228,14,16,58,264.604,...,0,1,2,0,0,1,65,172,22,120
255,9,18,8,3,1,228,14,16,58,265.615,...,0,1,2,0,0,1,65,172,22,8
620,9,25,3,3,2,228,14,16,58,222.196,...,0,1,2,0,0,1,65,172,22,3
727,9,6,7,2,1,228,14,16,58,264.604,...,0,1,2,0,0,1,65,172,22,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,27,23,9,3,1,184,42,7,27,241.476,...,0,1,0,0,0,0,58,167,21,2
149,27,23,2,3,2,184,42,7,27,302.585,...,0,1,0,0,0,0,58,167,21,8
132,27,23,1,5,2,184,42,7,27,308.593,...,0,1,0,0,0,0,58,167,21,2
269,27,6,8,4,1,184,42,7,27,265.615,...,0,1,0,0,0,0,58,167,21,8
118,27,23,1,5,2,184,42,7,27,308.593,...,0,1,0,0,0,0,58,167,21,2

In [43]:
#sort data berdasarkan lebih dari satu kolom

df.sort_values(['Seasons','Age'])

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
40,27,23,9,3,1,184,42,7,27,241.476,...,0,1,0,0,0,0,58,167,21,2
269,27,6,8,4,1,184,42,7,27,265.615,...,0,1,0,0,0,0,58,167,21,8
6,10,22,7,6,1,361,52,3,28,239.554,...,0,1,1,1,0,4,80,172,27,8
20,18,10,8,4,1,330,16,4,28,205.917,...,0,2,0,0,0,0,84,182,25,8
22,10,13,8,2,1,361,52,3,28,205.917,...,0,1,1,1,0,4,80,172,27,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,36,28,10,3,4,118,13,18,50,265.017,...,0,1,1,1,0,0,98,178,31,1
309,36,28,10,5,4,118,13,18,50,265.017,...,0,1,1,1,0,0,98,178,31,1
316,36,23,10,5,4,118,13,18,50,265.017,...,0,1,1,1,0,0,98,178,31,1
343,36,28,12,3,4,118,13,18,50,236.629,...,0,1,1,1,0,0,98,178,31,1
521,9,1,10,4,4,228,14,16,58,284.853,...,0,1,2,0,0,1,65,172,22,1

In [44]:
#sort data berdasarkan lebih dari satu kolom dengan ketentuan ascending atau descending

df.sort_values(['Seasons','Age'],ascending=[True, False])

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
255,9,18,8,3,1,228,14,16,58,265.615,...,0,1,2,0,0,1,65,172,22,8
727,9,6,7,2,1,228,14,16,58,264.604,...,0,1,2,0,0,1,65,172,22,8
729,9,6,7,3,1,228,14,16,58,264.604,...,0,1,2,0,0,1,65,172,22,120
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
237,36,1,7,4,1,118,13,18,50,275.312,...,0,1,1,1,0,0,98,178,31,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560,28,23,12,4,4,225,26,9,28,280.549,...,0,1,1,0,0,2,69,169,24,3
561,10,14,12,5,4,361,52,3,28,280.549,...,0,1,1,1,0,4,80,172,27,4
566,28,23,12,3,4,225,26,9,28,280.549,...,0,1,1,0,0,2,69,169,24,2
567,28,23,12,5,4,225,26,9,28,280.549,...,0,1,1,0,0,2,69,169,24,3
568,28,23,12,2,4,225,26,9,28,280.549,...,0,1,1,0,0,2,69,169,24,2

In [45]:
## secara default, sort_values tidak secara langsung mengubah struktur data jika tidak direplace

df_new = df.copy()
df_new.sort_values('Age')
df_new

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14,7,3,1,289,36,13,33,264.604,...,0,1,2,1,0,1,90,172,30,8
736,1,11,7,3,1,235,11,14,37,264.604,...,0,3,1,0,0,1,88,172,29,4
737,4,0,0,3,1,118,14,13,40,271.219,...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,271.219,...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0

In [46]:
## mekanisme sort_values baru akan langsung mengubah urutan data tanpa declaration apabila ditambahkan parameter inplace=True

df_new.sort_values('Age',inplace=True)
df_new

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
132,27,23,1,5,2,184,42,7,27,308.593,...,0,1,0,0,0,0,58,167,21,2
137,27,23,2,6,2,184,42,7,27,302.585,...,0,1,0,0,0,0,58,167,21,1
209,27,7,5,4,3,184,42,7,27,378.884,...,0,1,0,0,0,0,58,167,21,4
118,27,23,1,5,2,184,42,7,27,308.593,...,0,1,0,0,0,0,58,167,21,2
149,27,23,2,3,2,184,42,7,27,302.585,...,0,1,0,0,0,0,58,167,21,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,9,25,3,3,2,228,14,16,58,222.196,...,0,1,2,0,0,1,65,172,22,3
622,9,12,3,3,2,228,14,16,58,222.196,...,0,1,2,0,0,1,65,172,22,112
640,9,25,3,4,2,228,14,16,58,222.196,...,0,1,2,0,0,1,65,172,22,2
255,9,18,8,3,1,228,14,16,58,265.615,...,0,1,2,0,0,1,65,172,22,8
434,9,18,5,4,3,228,14,16,58,246.074,...,0,1,2,0,0,1,65,172,22,8

## Insert/Concat Dataframe

Inserting a row into Pandas DataFrame appends the row to the end of the DataFrame while leaving the original rows unchanged.

In [47]:
a_row = pd.Series([1, 2])
dfs = pd.DataFrame([[3, 4], [5, 6]])

row_df = pd.DataFrame([a_row])

dfs = pd.concat([dfs,row_df], ignore_index=True)
dfs

   0  1
0  3  4
1  5  6
2  1  2

## Mutate/Create new collumn

In [48]:
## Untuk membuat sebuah kolom baru yang merupakan turunan dari kolom yang lain

df['new_collumn'] = df['Age']+10
df[['Age','new_collumn']]

     Age  new_collumn
0     33           43
1     50           60
2     38           48
3     39           49
4     33           43
..   ...          ...
735   33           43
736   37           47
737   40           50
738   39           49
739   53           63

[740 rows x 2 columns]

```apply``` menerima setiap fungsi yang dibuat pengguna untuk menerapkan transformasi / agregasi pada DataFrame. apply secara efektif dapat menjalankan perintah apapun yang tidak tersedia pada fungsi bawaan pandas.

In [49]:
def grouping_age(age):
  if age>40:
    return True
  else:
    return False

df['flag_>40'] = df['Age'].apply(lambda x: grouping_age(x))
df[['Age','flag_>40']]

     Age  flag_>40
0     33     False
1     50      True
2     38     False
3     39     False
4     33     False
..   ...       ...
735   33     False
736   37     False
737   40     False
738   39     False
739   53      True

[740 rows x 2 columns]

pada function ```apply``` terdapat parameter axis yang digunakan untuk menentukan apakah fungsi yang di passing diterapkan secara colwise atau rowwise

In [50]:
df_sumrow = df[['Age','Hit target']].copy()

## set axis=1, fungsi sum akan diterapkan secara rowwise
df_sumrow['rowsum'] = df_sumrow.apply('sum',axis=1)
df_sumrow

     Age  Hit target  rowsum
0     33          97     130
1     50          97     147
2     38          97     135
3     39          97     136
4     33          97     130
..   ...         ...     ...
735   33          93     126
736   37          93     130
737   40          95     135
738   39          95     134
739   53          95     148

[740 rows x 3 columns]

## Compute

Untuk melakukan compute data, kita bisa menggunakan fungsi bawaan dari pandas seperti sum, mean, std, dll ataupun dengan menggunakan user-defined function dengan bantuan apply.
Yang terpenting adalah menentukan apakah proses komputasinya akan dilakukan secara rowwise atau colwise dengan ditentukan berdasarkan parameter axis.

In [51]:
## Compute nilai rata-rata/mean
df.mean(axis=0)

ID                                  18.017568
Reason for absence                  19.216216
Month of absence                     6.324324
Day of the week                      3.914865
Seasons                              2.544595
Transportation expense             221.329730
Distance from Residence to Work     29.631081
Service time                        12.554054
Age                                 36.450000
Work load Average/day              271.490235
Hit target                          94.587838
Disciplinary failure                 0.054054
Education                            1.291892
Son                                  1.018919
Social drinker                       0.567568
Social smoker                        0.072973
Pet                                  0.745946
Weight                              79.035135
Height                             172.114865
Body mass index                     26.677027
Absenteeism time in hours            6.924324
new_collumn                         46.450000
flag_>40                             0.190541
dtype: float64

In [52]:
## Compute nilai standar deviasi
df.std(axis=0)

ID                                 11.021247
Reason for absence                  8.433406
Month of absence                    3.436287
Day of the week                     1.421675
Seasons                             1.111831
Transportation expense             66.952223
Distance from Residence to Work    14.836788
Service time                        4.384873
Age                                 6.478772
Work load Average/day              39.058116
Hit target                          3.779313
Disciplinary failure                0.226277
Education                           0.673238
Son                                 1.098489
Social drinker                      0.495749
Social smoker                       0.260268
Pet                                 1.318258
Weight                             12.883211
Height                              6.034995
Body mass index                     4.285452
Absenteeism time in hours          13.330998
new_collumn                         6.478772
flag_>40                            0.392993
dtype: float64

In [53]:
pd.DataFrame({'sum':df.sum(),'mean':df.mean(),'median':df.median()})

                                        sum        mean   median
ID                                13333.000   18.017568   18.000
Reason for absence                14220.000   19.216216   23.000
Month of absence                   4680.000    6.324324    6.000
Day of the week                    2897.000    3.914865    4.000
Seasons                            1883.000    2.544595    3.000
Transportation expense           163784.000  221.329730  225.000
Distance from Residence to Work   21927.000   29.631081   26.000
Service time                       9290.000   12.554054   13.000
Age                               26973.000   36.450000   37.000
Work load Average/day            200902.774  271.490235  264.249
Hit target                        69995.000   94.587838   95.000
Disciplinary failure                 40.000    0.054054    0.000
Education                           956.000    1.291892    1.000
Son                                 754.000    1.018919    1.000
Social drinker                      420.000    0.567568    1.000
Social smoker                        54.000    0.072973    0.000
Pet                                 552.000    0.745946    0.000
Weight                            58486.000   79.035135   83.000
Height                           127365.000  172.114865  170.000
Body mass index                   19741.000   26.677027   25.000
Absenteeism time in hours          5124.000    6.924324    3.000
new_collumn                       34373.000   46.450000   47.000
flag_>40                            141.000    0.190541    0.000

Jika kita ingin membuat kolom baru pada dataframe yang nilainya merupakan statistik berdasarkan group tertentu kita bisa menggunakan kombinasi fungsi ```groupby``` dan ```transform```. Fungsi ini kurang lebih serupa dengan kombinasi antara groupby dan mutate pada dplyr di bahasa R.

In [54]:
df['age_mean'] = df.groupby('Seasons')['Age'].transform('mean')
df

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours,new_collumn,flag_>40,age_mean
0,11,26,7,3,1,289,36,13,33,239.554,...,1,0,1,90,172,30,4,43,False,36.764706
1,36,0,7,3,1,118,13,18,50,239.554,...,1,0,0,98,178,31,0,60,True,36.764706
2,3,23,7,4,1,179,51,18,38,239.554,...,1,0,0,89,170,31,2,48,False,36.764706
3,7,7,7,5,1,279,5,14,39,239.554,...,1,1,0,68,168,24,4,49,False,36.764706
4,11,23,7,5,1,289,36,13,33,239.554,...,1,0,1,90,172,30,2,43,False,36.764706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14,7,3,1,289,36,13,33,264.604,...,1,0,1,90,172,30,8,43,False,36.764706
736,1,11,7,3,1,235,11,14,37,264.604,...,0,0,1,88,172,29,4,47,False,36.764706
737,4,0,0,3,1,118,14,13,40,271.219,...,1,0,8,98,170,34,0,50,False,36.764706
738,8,0,0,4,2,231,35,14,39,271.219,...,1,0,2,100,170,35,0,49,False,35.848958
739,35,0,0,6,3,179,45,14,53,271.219,...,0,0,1,77,175,25,0,63,True,37.185792

In [55]:
def zscores(series):
  return (series-series.min())/series.std()

df.groupby('Seasons')['Age'].transform(zscores)

0      0.936530
1      3.590031
2      1.716971
3      1.873060
4      0.936530
         ...
735    0.936530
736    1.560883
737    2.029148
738    2.008103
739    3.726911
Name: Age, Length: 740, dtype: float64

In [56]:
def zscores_with_group(group):
  df = pd.DataFrame(
      {'Age':zscores(group['Age']),
       'Seasons':group['Seasons']
      }
  )
  return df

df.groupby('Seasons').apply(zscores_with_group).head()

<ipython-input-56-e7ecb3c62fa3>:9: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df.groupby('Seasons').apply(zscores_with_group).head()

        Age  Seasons
0  0.936530        1
1  3.590031        1
2  1.716971        1
3  1.873060        1
4  0.936530        1

## Apply vs Transform

Terdapat sejumlah perbedaan antara fungsi apply dan fungsi transform:
1. transform() works with function, a string function, a list of functions, and a dict. However, apply() is only allowed with function.
2. transform() cannot produce aggregated results.
3. apply() works with multiple Series at a time. But, transform() is only allowed to work with a single Series at a time.

### Contoh 1

In [57]:
#df[['Age','Weight']].apply('sqrt')

In [58]:
df[['Age','Weight']].apply(np.sqrt)

          Age     Weight
0    5.744563   9.486833
1    7.071068   9.899495
2    6.164414   9.433981
3    6.244998   8.246211
4    5.744563   9.486833
..        ...        ...
735  5.744563   9.486833
736  6.082763   9.380832
737  6.324555   9.899495
738  6.244998  10.000000
739  7.280110   8.774964

[740 rows x 2 columns]

In [59]:
df[['Age','Weight']].transform('sqrt')

          Age     Weight
0    5.744563   9.486833
1    7.071068   9.899495
2    6.164414   9.433981
3    6.244998   8.246211
4    5.744563   9.486833
..        ...        ...
735  5.744563   9.486833
736  6.082763   9.380832
737  6.324555   9.899495
738  6.244998  10.000000
739  7.280110   8.774964

[740 rows x 2 columns]

### Contoh 2

In [60]:
df.apply(lambda x:x.sum())

ID                                  13333.000
Reason for absence                  14220.000
Month of absence                     4680.000
Day of the week                      2897.000
Seasons                              1883.000
Transportation expense             163784.000
Distance from Residence to Work     21927.000
Service time                         9290.000
Age                                 26973.000
Work load Average/day              200902.774
Hit target                          69995.000
Disciplinary failure                   40.000
Education                             956.000
Son                                   754.000
Social drinker                        420.000
Social smoker                          54.000
Pet                                   552.000
Weight                              58486.000
Height                             127365.000
Body mass index                     19741.000
Absenteeism time in hours            5124.000
new_collumn                         34373.000
flag_>40                              141.000
age_mean                            26973.000
dtype: float64

In [61]:
#df.transform(lambda x:x.sum())

# Aggregating

Calculate summary statistics on DataFrame columns, and master grouped summary statistics and pivot tables

* Summarizing with:
  * `median()`, `mode()`, `min()`, `max()`, `median()`, `sum()`, `var()`, `std()`, `quantile()`
  * `cumsum()`, `cummin()`, `cummax()`, `cumprod()`,
* Counting
  * `drop_duplicates()`, `value_counts()`
* Grouped summary statistics with `groupby()`
* Pivot Tales
  * _They are just DataFrames with sorted indexes_
  * Filling missing values
  * Summing

## Summarize

In [62]:
# Jumlah baris pada dataset
df['Age'].count()

740

In [63]:
# Number of non-null unique Seasons entries
df['Seasons'].nunique()

4

In [64]:
# How many records are there for each Season?
df['Seasons'].value_counts()

4    195
2    192
3    183
1    170
Name: Seasons, dtype: int64

In [65]:
df[['Seasons','flag_>40']].value_counts(sort=True, normalize=True)

Seasons  flag_>40
2        False       0.227027
4        False       0.217568
3        False       0.183784
1        False       0.181081
3        True        0.063514
1        True        0.048649
4        True        0.045946
2        True        0.032432
dtype: float64

In [66]:
df['Age'].mean()

36.45

In [67]:
df.drop_duplicates(subset='Seasons')

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours,new_collumn,flag_>40,age_mean
0,11,26,7,3,1,289,36,13,33,239.554,...,1,0,1,90,172,30,4,43,False,36.764706
49,15,14,9,2,4,291,31,12,40,241.476,...,1,0,1,73,171,25,32,50,False,36.076923
111,24,19,12,6,2,246,25,16,41,261.306,...,1,0,0,67,170,23,8,51,True,35.848958
175,28,11,3,2,3,225,26,9,28,343.253,...,0,0,2,69,169,24,8,38,False,37.185792

## Summarizing by Group

In [68]:
df.groupby('Seasons')['Age'].mean()

Seasons
1    36.764706
2    35.848958
3    37.185792
4    36.076923
Name: Age, dtype: float64

In [69]:
df.groupby('Seasons')['Age'].agg('mean')

Seasons
1    36.764706
2    35.848958
3    37.185792
4    36.076923
Name: Age, dtype: float64

In [70]:
df.groupby('Seasons').agg(
    n = ('Age','count'),
    mean_age = ('Age','mean'),
    max_age = ('Age','max'),
    min_age =('Age','min'),
    mean_edu = ('Education','mean')
)

           n   mean_age  max_age  min_age  mean_edu
Seasons
1        170  36.764706       58       27  1.247059
2        192  35.848958       58       27  1.302083
3        183  37.185792       58       27  1.404372
4        195  36.076923       58       28  1.215385

Pada fungsi ```agg```, kita bisa menggunakan custom aggregation juga sebagaimana yang dapat dilakukan pada fungsi ```apply```

In [71]:
def get_diff(series):
  return series.max()-series.min()

df.groupby('Seasons').agg(
    n = ('Age','count'),
    mean_age = ('Age','mean'),
    max_age = ('Age','max'),
    min_age =('Age','min'),
    mean_edu = ('Education','mean'),
    age_diff = ('Age',get_diff)
)

           n   mean_age  max_age  min_age  mean_edu  age_diff
Seasons
1        170  36.764706       58       27  1.247059        31
2        192  35.848958       58       27  1.302083        31
3        183  37.185792       58       27  1.404372        31
4        195  36.076923       58       28  1.215385        30

In [72]:
df.groupby(['Seasons','Day of the week']).agg(
    n = ('Age','count'),
    mean_age = ('Age','mean'),
    max_age = ('Age','max'),
    min_age =('Age','min'),
    mean_edu = ('Education','mean')
).reset_index()

    Seasons  Day of the week   n   mean_age  max_age  min_age  mean_edu
0         1                2  39  37.051282       58       28  1.230769
1         1                3  44  37.022727       58       27  1.272727
2         1                4  27  35.851852       50       27  1.148148
3         1                5  31  37.032258       50       28  1.419355
4         1                6  29  36.551724       50       28  1.137931
5         2                2  42  35.928571       50       28  1.357143
6         2                3  42  36.476190       58       27  1.261905
7         2                4  40  35.925000       58       28  1.150000
8         2                5  34  34.647059       49       27  1.352941
9         2                6  34  36.088235       47       27  1.411765
10        3                2  42  36.000000       50       28  1.357143
11        3                3  24  38.625000       50       28  1.125000
12        3                4  49  37.918367       58       27  1.326531
13        3                5  27  37.629630       50       28  1.444444
14        3                6  41  36.390244       53       28  1.682927
15        4                2  38  36.105263       47       28  1.236842
16        4                3  44  34.931818       50       28  1.113636
17        4                4  40  35.925000       58       28  1.300000
18        4                5  33  37.666667       50       28  1.333333
19        4                6  40  36.150000       50       28  1.125000

In [73]:
grouped = df.groupby('Seasons')[['Age','Weight']].agg(['min','max','mean'])

grouped

        Age                Weight
        min max       mean    min  max       mean
Seasons
1        27  58  36.764706     56  108  80.288235
2        27  58  35.848958     56  108  78.104167
3        27  58  37.185792     56  106  79.016393
4        28  58  36.076923     56  108  78.876923

In [74]:
grouped = df.groupby('Seasons').agg(
    {
        'Age': ['min', 'max', 'sum'],
        'Weight': ['mean', 'nunique']
    }
)

grouped

        Age               Weight
        min max   sum       mean nunique
Seasons
1        27  58  6250  80.288235      24
2        27  58  6883  78.104167      24
3        27  58  6805  79.016393      24
4        28  58  7035  78.876923      20

In [75]:
# Using ravel, and a string join, we can create better names for the columns:
grouped.columns = ["_".join(x) for x in grouped.columns.ravel()]
grouped

<ipython-input-75-15091261cf0a>:2: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  grouped.columns = ["_".join(x) for x in grouped.columns.ravel()]

         Age_min  Age_max  Age_sum  Weight_mean  Weight_nunique
Seasons
1             27       58     6250    80.288235              24
2             27       58     6883    78.104167              24
3             27       58     6805    79.016393              24
4             28       58     7035    78.876923              20

## Pivot table

Pivot table is a table of statistics that helps summarize the data of a larger table by “pivoting” that data into two or more dimensions.

In [76]:
df.pivot_table(values="Age", index="Seasons", aggfunc=["mean", "median","std"])

              mean median       std
               Age    Age       Age
Seasons
1        36.764706     37  6.406629
2        35.848958     37  5.975789
3        37.185792     37  6.976288
4        36.076923     37  6.498154

In [77]:
df.pivot_table(values="Age", index="Seasons", columns="Day of the week",aggfunc='median')

Day of the week     2     3     4     5     6
Seasons
1                37.0  37.0  36.0  38.0  36.0
2                37.0  37.0  38.0  35.5  38.0
3                36.5  38.0  37.0  37.0  36.0
4                37.0  37.0  36.5  38.0  36.0

# Transforming Data

## Change data column

In [78]:
df_mpg = pd.read_csv('https://raw.githubusercontent.com/arjun-majumdar/auto_mpg_dataset/master/auto-mpg.csv')

df_mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [79]:
df_mpg['sqrt_weight'] = df_mpg['weight'].transform('sqrt')
df_mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,sqrt_weight
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,59.194594
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,60.770058
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,58.617404
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,58.591808
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,58.728187

## Renaming data

In [80]:
df_rename = df_mpg[['mpg','car name']]
df_rename.columns = ['miles_per_galon','car_name']
df_rename

     miles_per_galon                   car_name
0               18.0  chevrolet chevelle malibu
1               15.0          buick skylark 320
2               18.0         plymouth satellite
3               16.0              amc rebel sst
4               17.0                ford torino
..               ...                        ...
393             27.0            ford mustang gl
394             44.0                  vw pickup
395             32.0              dodge rampage
396             28.0                ford ranger
397             31.0                 chevy s-10

[398 rows x 2 columns]

In [81]:
df_mpg.rename(columns={'mpg':'miles_per_galon','car name':'car_name'}).head()

,miles_per_galon,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car_name,sqrt_weight
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,59.194594
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,60.770058
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,58.617404
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,58.591808
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,58.728187

In [82]:
df_mpg.add_prefix('mpg_').head()

,mpg_mpg,mpg_cylinders,mpg_displacement,mpg_horsepower,mpg_weight,mpg_acceleration,mpg_model year,mpg_origin,mpg_car name,mpg_sqrt_weight
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,59.194594
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,60.770058
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,58.617404
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,58.591808
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,58.728187

In [83]:
df_mpg.add_suffix('_mpg').head()

,mpg_mpg,cylinders_mpg,displacement_mpg,horsepower_mpg,weight_mpg,acceleration_mpg,model year_mpg,origin_mpg,car name_mpg,sqrt_weight_mpg
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,59.194594
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,60.770058
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,58.617404
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,58.591808
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,58.728187

## Removing data

In [84]:
df_mpg.shape

(398, 10)

In [85]:
df_mpg.groupby('cylinders').agg(
    {'mpg':'min',
     'cylinders':'count'}
)

            mpg  cylinders
cylinders
3          18.0          4
4          18.0        204
5          20.3          3
6          15.0         84
8           9.0        103

In [86]:
df_mpg_filter = df_mpg.groupby('cylinders').filter(lambda x: x['mpg'].min()>=15)
df_mpg_filter.shape

(295, 10)

## Merge, join, and concatenate

### we start with concatenate
The concat() function (in the main pandas namespace) does all of the heavy lifting of performing concatenation operations along an axis while performing optional set logic (union or intersection) of the indexes (if any) on the other axes.

![concat](https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_basic.png)

In [87]:
df1 = pd.DataFrame(
  {
    "A": ["A0", "A1", "A2", "A3"],
    "B": ["B0", "B1", "B2", "B3"],
    "C": ["C0", "C1", "C2", "C3"],
    "D": ["D0", "D1", "D2", "D3"],
  }
)


df2 = pd.DataFrame(
  {
    "A": ["A4", "A5", "A6", "A7"],
    "B": ["B4", "B5", "B6", "B7"],
    "C": ["C4", "C5", "C6", "C7"],
    "D": ["D4", "D5", "D6", "D7"],
  }
)

df3 = pd.DataFrame(
  {
    "A": ["A8", "A9", "A10", "A11"],
    "B": ["B8", "B9", "B10", "B11"],
    "C": ["C8", "C9", "C10", "C11"],
    "D": ["D8", "D9", "D10", "D11"],
  }
)

df4 = pd.DataFrame(
  {
    "B": ["B2", "B3", "B6", "B7"],
    "D": ["D2", "D3", "D6", "D7"],
    "F": ["F2", "F3", "F6", "F7"],
  }
)

result = pd.concat([df1, df2, df3])
result.reset_index(drop=True)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [88]:
## cara lainnya, kita bisa menggunakan append

result = df1.append(df2)
result

<ipython-input-88-5e1f5abc2975>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = df1.append(df2)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [89]:
## append data tidak harus memiliki struktur variable/kolom yang sama persis
result = df1.append(df4,ignore_index=True)
result

<ipython-input-89-81df35cf6609>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = df1.append(df4,ignore_index=True)

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

### Join and merge data

In [90]:
result = pd.concat([df1, df4], axis=1)
result

    A   B   C   D   B   D   F
0  A0  B0  C0  D0  B2  D2  F2
1  A1  B1  C1  D1  B3  D3  F3
2  A2  B2  C2  D2  B6  D6  F6
3  A3  B3  C3  D3  B7  D7  F7

Pada proses integrasi data, merging atau joining data umumnya dilakukan dengan berdasarkan key value.
Untuk melakukannya, kita bisa menggunakan fungsi merge dan menambahkan argumen key. Secara default, mekanisme merge dilakukan secara *inner join*.  

![merge](https://pandas.pydata.org/pandas-docs/stable/_images/merging_merge_on_key.png)

In [91]:
left = pd.DataFrame(
  {
    "key": ["K0", "K1", "K2", "K3"],
    "A": ["A0", "A1", "A2", "A3"],
    "B": ["B0", "B1", "B2", "B3"],
  }
)

right = pd.DataFrame(
  {
    "key": ["K0", "K1", "K2", "K3"],
    "C": ["C0", "C1", "C2", "C3"],
    "D": ["D0", "D1", "D2", "D3"],
  }
)

result = pd.merge(left, right, on="key")
result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [92]:
left = pd.DataFrame(
  {
    "key1": ["K0", "K0", "K1", "K2"],
    "key2": ["K0", "K1", "K0", "K1"],
    "A": ["A0", "A1", "A2", "A3"],
    "B": ["B0", "B1", "B2", "B3"],
  }
)

right = pd.DataFrame(
  {
    "key1": ["K0", "K1", "K1", "K2"],
    "key2": ["K0", "K0", "K0", "K0"],
    "C": ["C0", "C1", "C2", "C3"],
    "D": ["D0", "D1", "D2", "D3"],
  }
)

result = pd.merge(left, right, on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

Mekanisme merging data berdasarkan key value dapat dibagi menjadi beberapa cara:
1. left : menggunakan key dari left dataframe sebagai referensi
2. right : menggunakan key dari right dataframe sebagai referensi
3. outer : menggunakan gabungan key dari left dan right dataframe sebagai referensi
4. inner : menggunakan key dari left dan right dataframe yang hanya beririsan sebagai referensi

In [93]:
pd.merge(left, right, how="left", on=["key1", "key2"])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [94]:
pd.merge(left, right, how="right", on=["key1", "key2"])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [95]:
pd.merge(left, right, how="outer", on=["key1", "key2"])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

Sumber :

[Github](https://github.com/wblakecannon/DataCamp)

[NumPy](https://numpy.org/)

[Pandas](https://pandas.pydata.org/)

[Python](https://docs.python.org/)